---
# tasks file for telegram_bot_service
- name: Create and Activate env
  shell: |
    virtualenv mypython
    source mypython/bin/activate
    
- name: Copy script files
  copy: src={{ item }} dest={{ path }} mode=0555
  loop: 
    - "main.py"
    - "config.py"
    - "pip-requirements.txt"

- name: Install Python Packages
  shell: pip install -r {{ path }}/pip-requirements.txt

- name: Generate MAIN.PY file
  template: src=bot.service.j2 dest={{ destin }} mode=0555

- name: Start service
  shell: |
    systemctl daemon-reload
    systemctl enable bot.service
    systemctl start bot.service
